# Branch Protection Rules Configuration
# This file documents the branch protection rules that should be applied
# to the Kenya Crypto-Fiat Payment Processor repository

branch_protection_rules:
  main:
    # Protect the main branch with strict rules
    required_status_checks:
      strict: true
      contexts:
        - "Backend Tests"
        - "Frontend Tests" 
        - "Security Scan"
        - "JIRA Integration"
        - "Code Quality Check"
    
    enforce_admins: true
    required_pull_request_reviews:
      required_approving_review_count: 2
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
      restrict_pushes: true
    
    restrictions:
      users: []
      teams: []
      apps: []
    
    required_linear_history: true
    allow_force_pushes: false
    allow_deletions: false
    block_creations: false

  develop:
    # Protect the develop branch with moderate rules
    required_status_checks:
      strict: true
      contexts:
        - "Backend Tests"
        - "Frontend Tests"
        - "JIRA Integration"
    
    enforce_admins: false
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: false
    
    allow_force_pushes: false
    allow_deletions: false