# This is the default docker-compose.yml for development.
# It uses the docker-compose.dev.yml for actual services.
# This file primarily serves as a placeholder or for simple `docker-compose up`
# which will then default to the dev configuration.
version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:14-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-dev.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: kcb_crypto_fiat_dev_db
      POSTGRES_USER: kcb_user
      POSTGRES_PASSWORD: kcb_password_secure
    ports:
      - "5432:5432"
    networks:
      - app-network

  # Frontend service (Next.js) - will be added in later levels
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app/frontend
  #     - /app/frontend/node_modules
  #   env_file:
  #     - ./frontend/.env.local
  #   depends_on:
  #     - backend
  #   networks:
  #     - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
